use_frameworks!

platform :ios, '10.0'

target 'TXPageKit_Example' do
  pod 'TXPageKit', :path => '../'
  
  pod 'HMSegmentedControl', '1.5.6'

  target 'TXPageKit_Tests' do
    inherit! :search_paths

    
  end
end
